package nz.ac.auckland.se281.datastructures;

/**
 * An edge in a graph that connects two verticies.
 *
 * <p>You must NOT change the signature of the constructor of this class.
 *
 * @param <T> The type of each vertex.
 */
public class Edge<T> {

  // Initialising the source and destination

  private T source;
  private T destination;

  // Creating the constructor

  public Edge(T source, T destination) {
    this.source = source;
    this.destination = destination;
  }

  // Creating methods for the getters

  public T getSource() {
    return source;
  }

  public T getDestination() {
    return destination;
  }

  // Creating overide methods for the hashcode and equals, to compare to edges.
  // Autogenerated by VS CODE

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;

    // Creating the formula for hashcode

    result = prime * result + ((source == null) ? 0 : source.hashCode());
    result = prime * result + ((destination == null) ? 0 : destination.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object obj) {

    // Checking if it is the same instance as the object or if it is null

    if (this == obj) {
      return true;
    }

    if (obj == null) {
      return false;
    }

    if (getClass() != obj.getClass()) {
      return false;
    }
    // Casting the object to an edge

    Edge<T> other = (Edge) obj;

    // Checking for equality

    if (source == null) {
      if (other.source != null) {
        return false;
      }
    } else if (!source.equals(other.source)) {
      return false;
    }
    if (destination == null) {
      if (other.destination != null) {
        return false;
      }
    } else if (!destination.equals(other.destination)) {
      return false;
    }
    return true;
  }
}
